handle login register
awesome-academy/ios-nd-petty pull request #8
Opened 2019-04-09 09:34 UTC by chuongmd-1771

### Issue Link :link:

https://edu-redmine.sun-asterisk.vn/issues/10014
### Goals :soccer:

- handle login register
### Implementation Details :construction:

2019-04-09 10:07 UTC, chuongmd-1771 commented
ready

2019-04-10 01:45 UTC, tienpx3010 commented on Petty/Application/AppDelegate.swift
> +        let navigateToLogin = storyBoard.instantiateViewController(withIdentifier: Constant.loginViewController)
Sử dụng Reusable

2019-04-10 01:45 UTC, tienpx3010 commented on Petty/Application/AppDelegate.swift
> +        let userDefaults = UserDefaults.standard
Cho vào một func

2019-04-10 01:45 UTC, tienpx3010 commented on Petty/Extensions/UIViewController+.swift
> +    func registerSuccessAlert() {
```suggestion
    func showRegisterSuccessAlert() {
```

2019-04-10 01:45 UTC, tienpx3010 commented on Petty/Scenes/Common/Constant.swift
> +    static let loginViewController = "LoginViewController"
Bỏ

2019-04-10 01:45 UTC, tienpx3010 commented on Petty/Scenes/Home/HomeViewController.swift
> +    static let sceneStoryboard = Storyboard.mainStoryBoard
Cho vào extension

2019-04-10 01:45 UTC, tienpx3010 commented on Petty/Scenes/Login/LoginViewController.swift
> +            emailAlreadyInUseAlert()
```suggestion
            showEmailAlreadyInUseAlert()
```

2019-04-10 01:45 UTC, tienpx3010 commented on Petty/Application/AppDelegate.swift
> +        let storyBoard = Storyboard.mainStoryBoard
Bỏ

2019-04-10 01:45 UTC, tienpx3010 commented on Petty/Scenes/Storyboard/Storyboards.swift
> +enum Storyboard {
```suggestion
enum Storyboards {
```

2019-04-10 01:45 UTC, tienpx3010 commented on Petty/Scenes/Storyboard/Storyboards.swift
> +    static let mainStoryBoard = UIStoryboard(name: "Main", bundle: nil)
```suggestion
    static let main = UIStoryboard(name: "Main", bundle: nil)
```

2019-04-10 03:08 UTC, chuongmd-1771 commented
ready

2019-04-10 03:19 UTC, tienpx3010 commented on Petty/Application/AppDelegate.swift
> +    func checkAppFirstTimeOpend() {
```suggestion
    func checkIfAppRunFirstTime() {
```

2019-04-10 03:19 UTC, tienpx3010 commented on Petty/Application/AppDelegate.swift
> +            window?.rootViewController = navigateToHome
guard let

2019-04-10 03:19 UTC, tienpx3010 commented on Petty/Scenes/Home/HomeViewController.swift
> +    static var sceneStoryboard = Storyboards.main
Bỏ vào extension

2019-04-10 05:59 UTC, chuongmd-1771 commented
ready

2019-04-10 06:13 UTC, chuongmd-1771 commented
ready

2019-04-10 07:02 UTC, chuongmd-1771 commented
ready

2019-04-10 07:52 UTC, tienpx3010 requested changes

2019-04-10 07:52 UTC, tienpx3010 commented on Petty/Application/AppDelegate.swift
> +        if userDefaults.value(forKey: "appFirstTimeOpend") == nil {
Sai tiếng anh

2019-04-10 07:52 UTC, tienpx3010 commented on Petty/Application/AppDelegate.swift
> +        guard let windows = window else { return }
Để lên đầu

2019-04-10 07:52 UTC, tienpx3010 commented on Petty/Application/AppDelegate.swift
> +            if user != nil {
```suggestion
            windows.rootViewController = user != nil ? navigateToHome: navigateToLogin
```

2019-04-10 07:53 UTC, tienpx3010 commented
(commented)

2019-04-10 07:53 UTC, tienpx3010 commented
commented

2019-04-10 08:12 UTC, chuongmd-1771 commented
ready

2019-04-10 09:13 UTC, chuongmd-1771 commented
ready

2019-04-10 09:52 UTC, tienpx3010 approved these changes

2019-04-10 09:52 UTC, merged